### ISSUE TITLE
two sided = two sample?

### ISSUE THREAD

**Issue by mrshirts** [UWDIRECT/UWDIRECT.github.io#4]
I believe in UWDIRECT.github.io/Wi19_content/DSMCER/L5_Hypothesis_testing_filled.ipynb, the references to "two-sided" and "one-sided" should be "two sample" and "one sample".  One sided and two sided refer to different hypotheses to test.

**Comment by dacb** [comment]
This was addressed by a notebook rework several years ago: [dc54cf5](https://github.com/UWDIRECT/UWDIRECT.github.io/commit/dc54cf51e7d9142292f90c6ce8d81918acd842c1).  Thanks!
