### ISSUE TITLE
L6_MLIntro.ipynb

### ISSUE THREAD

**Issue by mrshirts** [UWDIRECT/UWDIRECT.github.io#5]
If you use all of the neighbors in the KNN example, it should go all blue, since there are more blue.  But the graph is all red, since the colormap normalizes it all to zero (classifying is still done correctly) I fixed this with:

plt.pcolormesh(xx, yy, Z, cmap=cmap_light,vmin=0,vmax=np.max(y))

instead of:

plt.pcolormesh(xx, yy, Z, cmap=cmap_light,vmin=0)

Not sure if there's a more elegant way.

**Comment by ccurtis7** [comment]
Thanks @mrshirts, I have updated the most recent version of `L6_MLIntro.ipynb` in the `Wi19_content/DSMCER` folder with your recommended changes, and made sure it behaved as you outlined. Thanks!
